---
- hosts: all
#  connection: local
 
  tasks:
    - name: debug
      debug:
        msg: '{{ item }}'
      #loop: '{{ local_accounts_list|dict2items }}'
      loop: '{{ local_accounts_list.values() | selectattr("group", "defined") | map(attribute="group")| default("")| list | unique }}'
